# Generated by Django 4.1.7 on 2023-04-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_task_datetime_alter_task_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
